
create TABLE IF NOT EXISTS person(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	surname VARCHAR(255) NOT NULL
);

create TABLE IF NOT EXISTS post(
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	user_id INTEGER,
	FOREIGN KEY (user_id) REFERENCES person (id)
); 